codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 50%
        threshold: 4%
        flags:
          - server
    patch:
      default:
        target: 50%
        threshold: 5%
        flags:
          - server

ignore:
  - "client/**"
  - "server/src/**/__tests__/**"
  - "**/*.test.ts"
  - "**/*.e2e.test.ts"
  - "**/*.d.ts"
  - "node_modules/**"

comment: false
